---
- hosts: all
  connection: local
  become: true


  pre_tasks:
  - name: Ensure sshd is installed (ALL)
    package:
      name: openssh-server
      state: present

  - name: Ensure sshd is running (ALL)
    service:
      name: sshd
      state: started
      enabled: yes

  - name: Ensure that the brentwg account was created (RedHat)
    user:
      name: brentwg
      comment: "Brent G."
      state: present
      group: brentwg
      groups: wheel
      append: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa


  tasks:
  - import_role:
      name: additional_packages
    vars:
      install_all_package_updates: true
      
  - name: Enable NOPASSWD for wheel group (RHEL)
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%wheel\s'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    when: ansible_os_family == 'RedHat'

  - name: Disable SELinux (RHEL)
    lineinfile:
      path: /etc/selinux/config
      state: present
      regexp: '^SELINUX='
      line: 'SELINUX=disabled'
    when: ansible_os_family == 'RedHat'

  - name: Modify .bashrc file (Fedora)
    blockinfile:
      path: "~/.bashrc"
      state: present
      insertafter: "# User specific aliases and functions"
      block: |
        alias update='sudo dnf update'
        alias trimssd='sudo fstrim -av'
    when: ansible_os_family == 'RedHat' and ansible_distribution == "Fedora"
    become_user: brentwg

  - import_role:
      name: brentwg.packer
    vars:
      packer_version: "1.2.0"
      packer_arch: "amd64"

  - import_role:
      name: brentwg.terraform
    vars:
      terraform_version: "0.11.3"
      terraform_arch: "amd64"

  - import_role:
      name: brentwg.visual-studio-code

  - import_role:
      name: brentwg.google-chrome

  - import_role:
      name: brentwg.docker

  - name: Add brentwg to the docker group
    user:
      name: brentwg
      groups: docker
      append: yes
 
