---
- hosts: all
  connection: local
  become: true


  pre_tasks:
  - name: Ensure sshd is installed
    package:
      name: openssh-server
      state: present

  - name: Ensure sshd is running
    service:
      name: sshd
      state: started
      enabled: yes


  tasks:
  - import_role:
      name: additional_packages
  - import_role:
      name: brentwg.packer
    vars:
      packer_version: "1.2.0"
      packer_arch: "amd64"
  - import_role:
      name: brentwg.terraform
    vars:
      terraform_version: "0.11.3"
      terraform_arch: "amd64"

