---
- name: Install additional group packages (Fedora)
  dnf:
    name: "@{{ item }}"
    state: present
  with_items: "{{ additional_groups }}"

- name: Install RPM Fusion Repos (Fedora)
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Install Media Codecs and VLC (Fedora)
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - gstreamer-plugins-base 
    - gstreamer1-plugins-base 
    - gstreamer-plugins-bad 
    - gstreamer-plugins-ugly 
    - gstreamer1-plugins-ugly 
    - gstreamer-plugins-good-extras 
    - gstreamer1-plugins-good-extras 
    - gstreamer1-plugins-bad-freeworld 
    - ffmpeg 
    - gstreamer-ffmpeg
    - vlc

