---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when:
    - ansible_os_family != 'Debian'
    - ansible_distribution != 'Fedora'

- name: Include OS-specific variables for Fedora.
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Fedora'

# Setup/install tasks
- name: Install all software package updates
  package:
    name: "*"
    state: "latest"
  when: install_all_package_updates

- name: Install additional packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ additional_packages }}"

# Deal with distro-specific tasks
- include_tasks: "{{ ansible_distribution }}.yml"
